### PR TITLE
Added job checking with support for multiple jobs.

### PR DESCRIPTION
**Pull request by LiamDormon**
By default the config is set to use ESX, but if disables allows the user to return their framework's PlayerJob object.

### CODE REVIEW

**Comment by deenz-dev** [comment]
Its not working mate, take a look at it again :/

**Comment by LiamDormon** [comment]
Do you get an error? This is working for me on Non-ESX. Edit: Fixed syntax error left over from when I copied it to github.

**Comment by deenz-dev** [comment]
Screenshot_1
Maybe cause the line 12? an "if" outside a function... xd

**Comment by LiamDormon** [comment]
Should be fixed by loading the config before the client script in the fxmanifest, tried and tested this morning without issues

**Comment by deenz-dev** [comment]
I had some errors anyways, can i add you on Discord?

**Comment by LiamDormon** [comment]
AFAIK everything in this build is working, tried and tested.

**Comment by deenz-dev** [comment]
Screenshot_2

**Comment by deenz-dev** [comment]
Also, update README, 
        job = {"police", "ambulance", "mechanic"}, <-- not working without this (comma, obv)
        distance = 1.5

**Comment by LiamDormon** [comment]
You must be doing something wrong because this works :) I loaded it up on my ESX server and my QB Server and on both it returned correctly.

**Comment by deenz-dev** [comment]
i didnt change anything tbh

**Pull request merged**
